apiVersion: v1
description: Service to subscribe to NATS streaming and persist audit events
name: audit
version: 2.8.0
appVersion: 1.6.0
keywords:
home: https://www.qlik.com
sources:
  - https://github.com/qlik-trial/audit
